# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual"

addons:
   apt:
     update: true
     sources:
       - sourceline: 'ppa:opencpu/imagemagick'
     packages:
       - libmagick++-dev

r_packages:
  - covr
  - ape
  - graphics
  - grDevices
  - pheatmap
  - phytools
  - stats
  - utils
  - methods
  - caper
  - scales

after_success:
  - Rscript -e 'covr::codecov()'
