# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

install:
  ## For installing all CRAN dependencies using rpack's DESCRIPTION
  - ./travis-tool.sh install_deps

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual"

addons:
   apt:
     update: true
     sources:
       - sourceline: 'ppa:opencpu/imagemagick'
       - sourceline: 'ppa:ubuntugis/ppa'
     packages:
       - libmagick++-dev
       - librsvg2-dev
       - libwebp-dev
       - libpoppler-cpp-dev
       - libtesseract-dev
       - libleptonica-dev
       - tesseract-ocr-eng
       - r-cran-rgdal
       - libfftw3-dev
       - cargo

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
