# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual"

addons:
   apt:
     update: true
     sources:
       - sourceline: 'ppa:opencpu/imagemagick'
     packages:
       - libmagick++-dev

install:
  ## For installing all CRAN dependencies using rpack's DESCRIPTION
  - ./travis-tool.sh install_deps

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
